language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  - sudo apt-get install info install-info
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - cl -l flexi-streams -l fiveam -e '(ql-util:without-prompting (ql:add-to-init-file))'

script:
  - cl -f $TRAVIS_BUILD_DIR/tests/travis.lisp

